---
title: 'GOVUK Template'

format:
  govuk-html

execute:
  echo: false
  warning: false
---

This template is an example of how to write a report in the **GOV.UK** style.


```{r drop down}
#| results: "asis"
source('_extensions/govuk/html_functions.R')

expander(title = 'Further information', 
         description = 'Details of the section that you may not want to show as part of the main page but as extra information for anyone particularly interested.')

```

## More Information 

You can learn more about controlling the appearance of HTML output here: <https://quarto.org/docs/output-formats/html-basics.html>

### Subheader info
Text which can also be linked to in TOC

::: {.panel-tabset}

## Tab 1

```{r Chart}

library(plotly)

fig <- plot_ly(
  data = iris,
  x = ~Sepal.Length,
  y = ~Petal.Length
) |> 
  config(displaylogo = FALSE,
         modeBarButtons = list(list("toImage")),
         toImageButtonOptions = list(format = "svg",
                                     filename = "Chart",
                                     width = 900,
                                     height = 640))

fig

```


## Tab 2

```{r Data table}

library(htmlTable)

htmlTable(head(iris, 10), rnames = FALSE)

```

:::

```{r Download button}

library(downloadthis)

iris |>
  download_this(
    output_name = 'My data',
    output_extension = ".csv",
    button_label = "Download data",
    button_type = "default",
    has_icon = FALSE,
    icon = "arrow-down-to-line",
    self_contained = TRUE,
    class = "govuk-button govuk-button--secondary",
    csv2 = FALSE
  )

```

## Further heading

More text here...

### A Subheading 

Different text here..

## Another heading

More text here...
