---
title: 'Standard Template'

format:
  govuk-standard-html

execute:
  echo: false
  warnings: false
  message: false
  
---

This template is an example of how individual HTML pages can be used as part of a wider **GOV.UK** website.


```{r drop down}
#| results: "asis"

source('_extensions/govuk-standard/html_functions.R')
  
drop_down('Further information', 'Details of the section that you may not want to show as part of the main page but as extra information for anyone particularly interested.')

```

## More Information 

You can learn more about controlling the appearance of HTML output here: <https://quarto.org/docs/output-formats/html-basics.html>


::: {.panel-tabset}

## Tab 1

```{r Chart}
#| warnings: false
#| message: false

library(plotly)

fig <- plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)

fig

```


## Tab 2

```{r Data table}

library(htmlTable)

htmlTable(head(iris, 10), rnames=FALSE)

```

:::

```{r Download button}

library(downloadthis)

iris %>%
  download_this(
    output_name = 'My data',
    output_extension = ".csv",
    button_label = "Download data",
    button_type = "default",
    has_icon = FALSE,
    icon = "arrow-down-to-line",
    self_contained = TRUE,
    class = "govuk-button govuk-button--secondary",
    csv2 = FALSE
  )

```

### Subheading

You can make sure that only the H2 headings show in the TOC by putting in the YAML **toc-depth: 2**

## Section 2

More info here 
