---
title: 'Website Template'

format:
  govuk-website-html
  
execute:
  echo: false
  warnings: false
  message: false
---

```{r}
#| output: false

source('_extensions/govuk-website/html_functions.R')
```

::: {.grid}
::: {.g-col-12 .g-col-sm-3}

```{r sidebar}
#| results: "asis"
  
html_sidebar(selected = 'Page 1', 
             names = c('Page 1','Page 2','Page 3'), 
             folder = 'folder',
             subnames = c('Section 1','Section 2','Section 3'))

```

:::

::: {.g-col-12 .g-col-sm-9}

# Website Template

This template is an example of how individual HTML pages can be created and built together to form a **GOV.UK** website.


```{r drop down}
#| results: "asis"
source('_extensions/govuk-standard/html_functions.R')

drop_down(title = 'Further information', 
          description = 'Details of the section that you may not want to show as part of the main page but as extra information for anyone
          particularly interested.')

```

## More Information 

You can learn more about controlling the appearance of HTML output here: <https://quarto.org/docs/output-formats/html-basics.html>


::: {.panel-tabset}

## Tab 1

```{r Chart}
#| warnings: false
#| message: false

library(plotly)

fig <- plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)

fig

```


## Tab 2

```{r Data table}

library(htmlTable)

htmlTable(head(iris, 10), rnames=FALSE)

```

:::

```{r Download button}

library(downloadthis)

iris %>%
  download_this(
    output_name = 'My data',
    output_extension = ".csv",
    button_label = "Download data",
    button_type = "default",
    has_icon = FALSE,
    icon = "arrow-down-to-line",
    self_contained = TRUE,
    class = "govuk-button govuk-button--secondary",
    csv2 = FALSE
  )

```

:::
:::
